## Упражнения по библиотеке Numpy

In [1]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [2]:
#ну допустим дан, верю
arr = np.arange(1, 16)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [3]:
arr[(arr>3)&(arr<8)]  = -arr[(arr>3)&(arr<8)]
arr


array([ 1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14, 15])

**2.** Заменить максимальный элемент случайного массива на 0

In [4]:
arr[np.argmax(arr)] = 0
arr

array([ 1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14,  0])

**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [13]:
arr2d_1 = np.array([[1, 2, 3], [7, 8, 9]])
arr2d_2 = np.array([[4, 5], [11, 12]])
print(f"first array:\n{arr2d_1},\n\nsecond array:\n{arr2d_2}\n")


first array:
[[1 2 3]
 [7 8 9]],

second array:
[[ 4  5]
 [11 12]]



In [33]:
def descartes(arr1, arr2):
    x, y = np.meshgrid(arr1, arr2, indexing='xy')
    result = np.column_stack((x.ravel(), y.ravel()))
    return result

In [34]:
result = descartes(arr2d_1, arr2d_2)
result

array([[ 1,  4],
       [ 2,  4],
       [ 3,  4],
       [ 7,  4],
       [ 8,  4],
       [ 9,  4],
       [ 1,  5],
       [ 2,  5],
       [ 3,  5],
       [ 7,  5],
       [ 8,  5],
       [ 9,  5],
       [ 1, 11],
       [ 2, 11],
       [ 3, 11],
       [ 7, 11],
       [ 8, 11],
       [ 9, 11],
       [ 1, 12],
       [ 2, 12],
       [ 3, 12],
       [ 7, 12],
       [ 8, 12],
       [ 9, 12]])

**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [59]:
arr_1 = np.random.randint(1, 9, (8, 3))
arr_2 = np.random.randint(1, 9, (2, 2))
print('first array 8x3\n', arr_1,'\nsecond array 2x2\n', arr_2)

first array 8x3
 [[8 5 4]
 [8 7 6]
 [5 2 5]
 [3 5 6]
 [8 3 3]
 [2 8 7]
 [6 8 7]
 [6 8 4]] 
second array 2x2
 [[8 3]
 [4 6]]


я правильно понимаю, что условие подразумевает, что если в В матрице 2х2 все 4 числа уникальных, а надо найти строки в А 8х3 где ВСЕ строки из В, то таких строк вовсе быть не может и надо просто заново рандомить?

In [74]:
#ну надеятся на то, что сгенерируется матрица с повторными значениями не буду, решу для построчной проверки элементов, а не наличия всех элементов матрицы в строках другой
string_indeces = []
for i in range(arr_1.shape[0]):
    x_row = arr_1[i]
    for j in range(arr_2.shape[0]):
        if (arr_2[j, 0] in x_row) and (arr_2[j, 1] in x_row):
            print(f'B row {arr_2[j]} is in the {i}th row in A: {x_row}')
            if i not in string_indeces:
                string_indeces.append(i)
        else:
            continue
if not string_indeces:
    print('better luck next time')


B row [8 3] is in the 4th row in A: [8 3 3]
B row [4 6] is in the 7th row in A: [6 8 4]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [93]:
arr = np.random.randint(1, 5, (10, 3))
arr

array([[4, 2, 3],
       [4, 4, 4],
       [4, 4, 4],
       [4, 3, 4],
       [1, 4, 4],
       [4, 3, 3],
       [4, 2, 1],
       [2, 3, 1],
       [1, 2, 3],
       [4, 3, 3]], dtype=int32)

In [95]:
nonunique_rows = []
for i in range(len(arr)):
    if np.unique(arr[i]).shape[0] == 1:
        print(f'{arr[i]} is not unique')
        nonunique_rows.append(i)
    else:
        print(f'{arr[i]} is unique')
print('indeces of a nonunique rows: ', nonunique_rows)
unique_arr = np.delete(arr, nonunique_rows, axis=0)
unique_arr

[4 2 3] is unique
[4 4 4] is not unique
[4 4 4] is not unique
[4 3 4] is unique
[1 4 4] is unique
[4 3 3] is unique
[4 2 1] is unique
[2 3 1] is unique
[1 2 3] is unique
[4 3 3] is unique
indeces of a nonunique rows:  [1, 2]


array([[4, 2, 3],
       [4, 3, 4],
       [1, 4, 4],
       [4, 3, 3],
       [4, 2, 1],
       [2, 3, 1],
       [1, 2, 3],
       [4, 3, 3]], dtype=int32)

**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [17]:
x = np.random.randint(1, 9)
arr_2d = np.random.randint(1, 9, (x, 2))
arr_2d

array([[8, 8],
       [3, 1],
       [7, 3],
       [8, 8],
       [5, 5]], dtype=int32)

In [20]:
new_arr_2d = np.unique(arr_2d, axis=0)
new_arr_2d

array([[3, 1],
       [5, 5],
       [7, 3],
       [8, 8]], dtype=int32)

______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [32]:
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
checker = np.full((5,3), 0)
min(len(X), len(X[0])) # использую для определения максимальной длины диагонали матрицы 

3

python only

In [ ]:
def diagonal_multiply(matrix):
    starting_point = 1
    zero_counter = 0
    for i in range(min(len(matrix), len(matrix[0]))):
        element = matrix[i][i]
        if element != 0:
            starting_point *= element
        else:
            zero_counter += 1
            continue
    if zero_counter == min(len(matrix), len(matrix[0])):
        print('unlucky bro, all diagonal elements are 0')
        return None
    else:
        return starting_point
    

In [65]:
diagonal_multiply(checker)
diagonal_multiply(X)

unlucky bro, all diagonal elements are 0


np.int64(3)

using numpy

In [46]:
def numpy_diagonal_multiply(matrix):
    diagonal = np.diag(matrix)
    product = np.prod(diagonal[diagonal != 0])
    if np.any(diagonal) == False:
        print('unlucky bro, all diagonal elements are 0')
        return None
    return product

In [67]:
numpy_diagonal_multiply(checker)
numpy_diagonal_multiply(X)

unlucky bro, all diagonal elements are 0


np.int64(3)

* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [89]:
#python one
x = np.array([1, 2, 2, 4])
y = np.array([2, 4, 1, 2])

In [79]:
def multiset_checker(vector_1, vector_2):
    x_cnt = {}
    for i in vector_1:
        x_cnt[i] = x_cnt.get(i, 0) + 1
    y_cnt = {}
    for i in vector_2:
        y_cnt[i] = y_cnt.get(i, 0) + 1
    return x_cnt == y_cnt

In [84]:
multiset_checker(x, y)

True

In [85]:
#numpy one
def numpy_multiset_checker(vector_1, vector_2):
    return np.array_equal(np.sort(vector_1), np.sort(vector_2))

In [90]:
numpy_multiset_checker(x, y)

True

* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [98]:
x = np.array([0, 9, 0, 3, 0, 0, 5, 7, 0])
y = np.array([0, -3, 6])

In [ ]:
#python one
def max_finder(arr):
    max = None
    for i in range(1, len(arr)):
        if arr[i - 1] == 0:
            if (max is None) or arr[i] > max:
                max = arr[i]
    return max

In [107]:
max_finder(y)

np.int64(-3)

In [109]:
#numpy one
def numpy_max_finder(arr):
    zero_idx = np.where(arr[:-1] == 0)[0]
    numbers_after_idx = zero_idx + 1
    numbers = arr[numbers_after_idx]
    return np.max(numbers)

In [112]:
numpy_max_finder(x)

np.int64(9)

* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [32]:
x = np.array([2, 2, 4, 3, 2, 3, 3])

In [ ]:
#python one
def RLE(arr):
    values = []
    streak = []
    count = 1
    for i in range(1, len(arr)):
        if arr[i] == arr[i-1]:
            count += 1
        else:
            values.append(arr[i-1])
            streak.append(count)
            count = 1
    values.append(arr[-1])
    streak.append(count)
    return list(map(int, values)), list(map(int, streak))

In [33]:
print(f'array is {x}\n\n encoded is: {RLE(x)}')

array is [2 2 4 3 2 3 3]

 encoded is: ([2, 4, 3, 2, 3], [2, 1, 1, 1, 2])


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [44]:
X = np.array([[0], [11]])
Y = np.array([[3], [-2]])

In [41]:
from scipy.spatial.distance import cdist
import time

In [ ]:
'''def distance(X, Y):
    return np.sqrt(np.sum(np.square(X - Y)))'''

In [46]:
def distance(X, Y):
    n = X.shape[0]
    m = Y.shape[0]
    matrix = np.zeros((n, m))
    for i in range(n):
        for j in range(m):
            diff = X[i] - Y[j]
            matrix[i, j] = np.sqrt(np.sum(diff**2))
    return matrix

In [79]:
np_time_s = time.time()
d1 = distance(X, Y)
np_time_f = time.time() - np_time_s
print(f'{d1} and np time is {np_time_f} sec\n\n')

sci_time_s = time.time()
d2 = cdist(X, Y, 'euclidean')
sci_time_f = time.time() - sci_time_s
z = (np_time_f/sci_time_f) * 100
print(f'{d2} and sci time is {sci_time_f} sec\n\n np / sci relation is {z:.3f}%')

[[ 3.  2.]
 [ 8. 13.]] and np time is 0.0003466606140136719 sec


[[ 3.  2.]
 [ 8. 13.]] and sci time is 0.00018072128295898438 sec

 np / sci relation is 191.821%


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [2]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [6]:
calorie_stats = np.loadtxt("./cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [12]:
avg_calories = np.mean(calorie_stats)
print(f'Main competitors on average have around {(avg_calories - 60):.3f} calories more than our product')

Main competitors on average have around 46.883 calories more than our product


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [13]:
calorie_stats_sorted = np.sort(calorie_stats)
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [17]:
median_calories = np.median(calorie_stats_sorted)
print(f'Mean    {avg_calories:.2f}\nMedian  {median_calories:.2f}')

Mean    106.88
Median  110.00


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [32]:
nth_percentile = 100
nth_value = 0
for i in np.arange(1, 100, 0.1):
    x = np.percentile(calorie_stats_sorted, i)
    if x > 60 and x < nth_percentile:
        nth_percentile = i
        nth_value = x
print(f'Min percentile that is greater than 60 calories is {nth_percentile:.2f}% with the value of {nth_value:.2f}')

Min percentile that is greater than 60 calories is 3.30% with the value of 60.16


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [33]:
more_calories = (np.sum(calorie_stats > 60)) * 100/(len(calorie_stats))
more_calories

np.float64(96.1038961038961)

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [34]:
calorie_std = np.std(calorie_stats)
calorie_std

np.float64(19.35718533390827)

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [ ]:
#самым сильным аргументом будет естественно являться значения калорийности и тот факт, что у 96% конкурентов они выше. Думаю это поможет поустойчивее закрепиться на рынке низкокалорийной продукции